########### 数据源配置 ###########
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kboot?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    druid:
          filters:
            - stat
            - wall
            - log4j
          stat-view-servlet:
            login-username: admin
            login-password: 123456
          pool-prepared-statements: true
          max-open-prepared-statements: 100
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths:
            - /**

mybatis:
  type-aliases-package: cc.sitec.kboot.model.pojo
  mapper-locations:
  - classpath:/mappers/*Mapper.xml

# 配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  notEmpty: false

logging:
  level:
    "cc.sitec.kboot.model": debug

server:
  port: 8088

# 自定义配置
# 超级管理的 id 和头像存储目录配置
system:
  super:
    user:
      id: 7
  avatar:
    dir:
